### ISSUE TITLE
上传符号报错 The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation.

### ISSUE THREAD

**Issue by CaffreySun** [BuglyDevTeam/Bugly-iOS#73]
##[error]errorMsg is : java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: java.lang.ExceptionInInitializerError
	at com.tencent.bugly.symtabtool.proguard.ft.<clinit>(Bugly:144)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:103)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:124)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:400)
	at com.tencent.bugly.symtabtool.proguard.ej.b(Bugly:14196)
	at com.tencent.bugly.symtabtool.proguard.ej.a(Bugly:15254)
	at com.tencent.bugly.symtabtool.ios.SymtabToolIos.main(Bugly:2088)
	... 16 more
Caused by: com.tencent.bugly.symtabtool.proguard.am: The chosen LogFactory implementation does not extend LogFactory. Please check your configuration. (Caused by java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1154)
	at com.tencent.bugly.symtabtool.proguard.ap.run(Bugly:960)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:957)
	at com.tencent.bugly.symtabtool.proguard.an.getFactory(Bugly:624)
	at com.tencent.bugly.symtabtool.proguard.an.getLog(Bugly:655)
	at com.tencent.bugly.symtabtool.proguard.fp.<init>(Bugly:60)
	at com.tencent.bugly.symtabtool.proguard.fq.<init>(Bugly:43)
	at com.tencent.bugly.symtabtool.proguard.fq.<clinit>(Bugly:45)
	... 23 more
Caused by: java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1108)
	... 31 more
 errorType is : 3 errorCode is : 3007
##[error]plugin execute result status: failure
##[error]error message: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: java.lang.ExceptionInInitializerError
	at com.tencent.bugly.symtabtool.proguard.ft.<clinit>(Bugly:144)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:103)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:124)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:400)
	at com.tencent.bugly.symtabtool.proguard.ej.b(Bugly:14196)
	at com.tencent.bugly.symtabtool.proguard.ej.a(Bugly:15254)
	at com.tencent.bugly.symtabtool.ios.SymtabToolIos.main(Bugly:2088)
	... 16 more
Caused by: com.tencent.bugly.symtabtool.proguard.am: The chosen LogFactory implementation does not extend LogFactory. Please check your configuration. (Caused by java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1154)
	at com.tencent.bugly.symtabtool.proguard.ap.run(Bugly:960)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:957)
	at com.tencent.bugly.symtabtool.proguard.an.getFactory(Bugly:624)
	at com.tencent.bugly.symtabtool.proguard.an.getLog(Bugly:655)
	at com.tencent.bugly.symtabtool.proguard.fp.<init>(Bugly:60)
	at com.tencent.bugly.symtabtool.proguard.fq.<init>(Bugly:43)
	at com.tencent.bugly.symtabtool.proguard.fq.<clinit>(Bugly:45)
	... 23 more
Caused by: java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1108)
	... 31 more

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
##[error]error type: 3
##[error]error code: 3007
##[error]errorMsg is : java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: java.lang.ExceptionInInitializerError
	at com.tencent.bugly.symtabtool.proguard.ft.<clinit>(Bugly:144)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:103)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:124)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:400)
	at com.tencent.bugly.symtabtool.proguard.ej.b(Bugly:14196)
	at com.tencent.bugly.symtabtool.proguard.ej.a(Bugly:15254)
	at com.tencent.bugly.symtabtool.ios.SymtabToolIos.main(Bugly:2088)
	... 16 more
Caused by: com.tencent.bugly.symtabtool.proguard.am: The chosen LogFactory implementation does not extend LogFactory. Please check your configuration. (Caused by java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1154)
	at com.tencent.bugly.symtabtool.proguard.ap.run(Bugly:960)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:957)
	at com.tencent.bugly.symtabtool.proguard.an.getFactory(Bugly:624)
	at com.tencent.bugly.symtabtool.proguard.an.getLog(Bugly:655)
	at com.tencent.bugly.symtabtool.proguard.fp.<init>(Bugly:60)
	at com.tencent.bugly.symtabtool.proguard.fq.<init>(Bugly:43)
	at com.tencent.bugly.symtabtool.proguard.fq.<clinit>(Bugly:45)
	... 23 more
Caused by: java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1108)
	... 31 more

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)] errorType is : 3 errorCode is : 3007
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: com.tencent.bk.devops.atom.task.a.a: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: java.lang.ExceptionInInitializerError
	at com.tencent.bugly.symtabtool.proguard.ft.<clinit>(Bugly:144)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:103)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:124)
	at com.tencent.bugly.symtabtool.proguard.k.a(Bugly:400)
	at com.tencent.bugly.symtabtool.proguard.ej.b(Bugly:14196)
	at com.tencent.bugly.symtabtool.proguard.ej.a(Bugly:15254)
	at com.tencent.bugly.symtabtool.ios.SymtabToolIos.main(Bugly:2088)
	... 16 more
Caused by: com.tencent.bugly.symtabtool.proguard.am: The chosen LogFactory implementation does not extend LogFactory. Please check your configuration. (Caused by java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1154)
	at com.tencent.bugly.symtabtool.proguard.ap.run(Bugly:960)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:957)
	at com.tencent.bugly.symtabtool.proguard.an.getFactory(Bugly:624)
	at com.tencent.bugly.symtabtool.proguard.an.getLog(Bugly:655)
	at com.tencent.bugly.symtabtool.proguard.fp.<init>(Bugly:60)
	at com.tencent.bugly.symtabtool.proguard.fq.<init>(Bugly:43)
	at com.tencent.bugly.symtabtool.proguard.fq.<clinit>(Bugly:45)
	... 23 more
Caused by: java.lang.ClassCastException: The application has specified that a custom LogFactory implementation should be used but Class 'org.apache.commons.logging.impl.LogFactoryImpl' cannot be converted to 'com.tencent.bugly.symtabtool.proguard.an'. Please check the custom implementation. Help can be found @http://commons.apache.org/logging/troubleshooting.html.
	at com.tencent.bugly.symtabtool.proguard.an.a(Bugly:1108)
	... 31 more

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.b(Unknown Source), com.tencent.bk.devops.atom.task.d.b.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.c.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	... 6 more

**Comment by JQShan1993** [comment]
相同的问题找不到问题
