### ISSUE TITLE
符号表工具 '3.3.4' 工具上传参数报错问题

### ISSUE THREAD

**Issue by dabing1022** [BuglyDevTeam/Bugly-iOS#77]
# 版本相关说明

- java

```sh
java -v
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
```

- 符号表工具：3.3.4

# 命令

```sh
java -jar buglyqq-upload-symbol.jar -appid xxx -appkey xxx -bundleid xxx -version xxx -platform IOS -inputSymbol xxx
```

报错：
```sh
Bugly(bugly.qq.com)符号表工具上传工具包 V1.0.48

用法 -- Usage
 java -jar buglyqq-upload-symbol.jar -appid <APP ID> -appkey <APP KEY> -bundleid <App BundleID> -version <App Version> -platform <App Platform> -inputSymbol <Original Symbol File Path> -inputMapping <Original mapping File Path>

参数说明 -- Introduction for arguments
 -appid APP ID of Bugly
 -appkey APP Key of Bugly
 -bundleid Android平台对应的是package name/iOS平台是Bundle Id
 -version APP版本，需要和bugly平台上面看到的crash版本号保持对齐
 -platform 平台类型包含三个选项 Android、IOS两个选项，注意大小写要正确
 -inputSymbol 原始符号表[ios是dsym/android平台是debug so]所在文件夹目录地址
 -inputMapping mapping所在文件夹目录地址[Android平台特有，ios忽略]

##[error]errorMsg is : 输入的原始符号表文件不存在! errorType is : 1 errorCode is : 1002
##[error]plugin execute result status: failure
##[error]error message: 输入的原始符号表文件不存在!
[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.a.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
##[error]error type: 1
##[error]error code: 1002
##[error]errorMsg is : 输入的原始符号表文件不存在!
[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.a.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)] errorType is : 1 errorCode is : 1002
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: com.tencent.bk.devops.atom.task.a.a: 输入的原始符号表文件不存在!
[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.a.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	... 6 more

```

请问是什么原因？我确认`-inputSymbol`参数的值已经给了，为什么报错了

```
##[error]errorMsg is : 输入的原始符号表文件不存在! errorType is : 1 errorCode is : 1002
```

**Comment by fixerx** [comment]
这个值要的是dsym所在的父目录, 并且dsym不能是压缩包, 只能是.dsym的格式

**Comment by dabing1022** [comment]
```
❯ tree
.
├── buglyqq-upload-symbol.jar
├── dsym
│   └── iphone_appstore_1.0.5_100_2021.07.02_17.33.03.ipa.dSYM
│       └── Contents
│           ├── Info.plist
│           └── Resources
│               └── DWARF
│                   ├── TMM
│                   ├── TMMPush
```

目前的目录是这样的，我的命令是

```bash
java -jar buglyqq-upload-symbol.jar -appid "123456" -appkey "123456" -bundleid "123456" -version "1.0.5" -platform IOS -inputSymbol dsym
```

部分数据脱敏处理了，仍然报上面的错误。

**Comment by huxq-coder** [comment]
遇到同样的问题，请问解决了吗

**Comment by dabing1022** [comment]
> 遇到同样的问题，请问解决了吗

暂时没。针对高崩溃的，先手动解析了。
