### ISSUE TITLE
上传符号表报错

### ISSUE THREAD

**Issue by qwerOC** [BuglyDevTeam/Bugly-iOS#91]
##[info]request upload Info Url is https://symbol-v2.bugly.qq.com/trpc.eff_tool.symbol_upload_gateway.SymbolUploadGateway/uploadInfo
##[info]request gitRepoUrl is null
##[info]request gitRepoBranch is null
##[info]request gitRepoHeadCommitId is null
##[info]envtype is null
##[info]getAppModuleList is null
##[info]retCode: 200 response message: {"statusCode":205102,"msg":"Failed at sign validate, auth failed, mysql error","uploadReqID":""}
##[error]errorMsg is : Failed at sign validate, auth failed, mysql error errorType is : 3 errorCode is : 205102
com.tencent.bk.devops.atom.task.a.a: Failed at sign validate, auth failed, mysql error
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
##[error]errorMsg is : com.tencent.bk.devops.atom.task.a.a: Failed at sign validate, auth failed, mysql error
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
 errorType is : 3 errorCode is : 2011
##[error]plugin execute result status: failure
##[error]error message: com.tencent.bk.devops.atom.task.a.a: Failed at sign validate, auth failed, mysql error
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.e.a.b(Unknown Source), com.tencent.bk.devops.atom.task.e.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
##[error]error type: 3
##[error]error code: 2011
##[error]errorMsg is : com.tencent.bk.devops.atom.task.a.a: Failed at sign validate, auth failed, mysql error
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.e.a.b(Unknown Source), com.tencent.bk.devops.atom.task.e.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)] errorType is : 3 errorCode is : 2011
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)
Caused by: com.tencent.bk.devops.atom.task.a.a: com.tencent.bk.devops.atom.task.a.a: Failed at sign validate, auth failed, mysql error
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.b(Unknown Source)
	at com.tencent.bk.devops.atom.task.e.a.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source)
	at com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153)
	at com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)

[com.tencent.bk.devops.atom.task.a.b.a(Unknown Source), com.tencent.bk.devops.atom.task.e.a.b(Unknown Source), com.tencent.bk.devops.atom.task.e.a.a(Unknown Source), com.tencent.bk.devops.atom.task.d.a.d.a(Unknown Source), com.tencent.bk.devops.atom.task.localtool.LocalTool.main(Unknown Source), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), com.tencent.bk.devops.atom.task.serivce.BuglyService.uploadSymbol(BuglyService.java:153), com.tencent.bk.devops.atom.task.localtool.QqLocalTool.main(QqLocalTool.java:20)]
	at com.tencent.bk.devops.atom.task.a.b.a(Unknown Source)

**Comment by qwerOC** [comment]
![image](https://user-images.githubusercontent.com/17760059/146898287-8d4e039a-9ee4-429c-aa5b-dd5d678d9120.png)
https://cloud.tencent.com/developer/ask/242114
这么样解决......
